#!/bin/bash

#clear the screen
clear

echo -ne "\033[32m";
# echo -e "\033[34m";
main_screen() {
cat <<EOF
+======================================================================+
|                  PLEASE CHOOSE YOUR WORKSPACE                        |
+----------------------------------------------------------------------+
|                         1) OFFICE (*)                                |
|                         2) HOME                                      |
+======================================================================+
EOF
}

office_screen() {
cat <<EOF
+======================================================================+
|          PLEASE CHOOSE REMOTE SERVER YOU WANT TO CONNECT             |
+----------------------------------------------------------------------+
|            1) SOLR DEVELOPMENT ENVIRONMENT(*)                        |
|            2) RABBITMQ DEVELOPMENT ENVIRONMENT                       |
|            3) SOLR TESTING ENVIRONMENT                               |
|            4) JETTY TESTING ENVIRONMENT                              |
|            5) 0X01 VIRTUALBOX ENVIRONMENT                            |
|            6) 0X02 VIRTUALBOX ENVIRONMENT                            |
|            7) 0X03 VIRTUALBOX ENVIRONMENT                            |
+======================================================================+
EOF
}

home_screen() {
cat <<EOF
+======================================================================+
|          PLEASE CHOOSE REMOTE SERVER YOU WANT TO CONNECT             |
+----------------------------------------------------------------------+
|            1) 0X01 VIRTUALBOX ENVIRONMENT                            |
|            2) 0X02 VIRTUALBOX ENVIRONMENT                            |
+======================================================================+
EOF
}

main_screen
read -p "CHOOSE WORKSPACE(1,2): " workspace

if [ -z "$workspace" ]; then
    workspace="1"
fi

case $workspace in
    1 ) office_screen;;
    2 ) home_screen;;
    * ) exit;;
esac

read -p "CHOOSE SERVER NUMBER: " server_type
if [ -z "$server_type" ]; then
    server_type="1"
fi

#reset color to normal
tput sgr0

if [ "$workspace" == "1" ]; then
case $server_type in
    1 ) pem_key="dev-env-solr.pem";;
    2 ) pem_key="rabbitmq-dev-env.pem";;
    3 ) pem_key="test-env-solr.pem";;
    4 ) pem_key="test-env-jetty.pem";;
    5 ) ssh gabriel@172.26.147.53;exit;;
    6 ) ssh gabriel@172.26.147.75;exit;;
    7 ) ssh gabriel@172.26.147.76;exit;;
    * ) exit;;
esac
else
case $server_type in
    1 ) ssh gabriel@192.168.0.2;exit;;
    2 ) ssh gabriel@192.168.0.3;exit;;
    * ) exit;;
esac
fi

# echo -e "\033[34m";

# the dir of pem keys
keys_dir=/home/gabriel/keys

# connect with remote server
if [ -z "$pem_key" ]; then
    echo -e "PLEASE INPUT THE NUMBER YOU CHOOSED!"
else
    while true; do
        read -p "PLEASE INPUT EC2 IP ADDRESS: " ip
        if [ -n "$ip" ]; then
            if [ "$ip" == "q" ]; then
                exit;
            fi
            break;
        fi
    done
    ssh -i $keys_dir/$pem_key ec2-user@$ip
fi
